/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import Code.ManejoUsuario;
import Code.Twits;
import Code.Usuario;

/**
 *
 * @author karen
 */
public class Interacciones extends javax.swing.JPanel {

    private ManejoUsuario user; 
   
    
    public Interacciones(ManejoUsuario user) {
        initComponents();
        this.user=user;
        
        mostrarMenciones();
        
    }
    
    public void mostrarMenciones() {
        if (user != null) { 
            Usuario usuarioActual = user.obtenerUsuarioActual(); 
            Twits[] mencionesGlobales = user.obtenerMencionesG();

            for (int i = mencionesGlobales.length - 1; i >= 0; i--) {
                Twits mencion = mencionesGlobales[i];

                Usuario creador = mencion.getUsuario();
                    
                if (mencion.getContenido().contains("@" + usuarioActual.getUsername()) && creador.isActivo()==true) {
                     men.append(mencion.toString() + "\n\n");
                }
            }
            
        } else {
            System.out.println("El usuario es null");
            }

            revalidate();
            repaint();
        
    }

     
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        men = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        setMaximumSize(new java.awt.Dimension(720, 490));
        setMinimumSize(new java.awt.Dimension(720, 490));
        setPreferredSize(new java.awt.Dimension(720, 490));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        men.setEditable(false);
        men.setBackground(new java.awt.Color(0, 0, 0));
        men.setColumns(20);
        men.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        men.setForeground(new java.awt.Color(255, 255, 255));
        men.setRows(5);
        jScrollPane1.setViewportView(men);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 700, 400));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menciones...");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 340, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea men;
    // End of variables declaration//GEN-END:variables
}
