/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import Code.ManejoUsuario;
import Code.Twits;

/**
 *
 * @author karen
 */
public class Interacciones extends javax.swing.JPanel {

    private ManejoUsuario user; 
    
    public Interacciones(ManejoUsuario user) {
        initComponents();
        this.user=user;
        mostrarMenciones();
    }
    
     public void mostrarMenciones() {
        men.setText("");
        
        Twits[] menciones = user.obtenerMencionActual();

        for (Twits mencion : menciones) {
            if (mencion != null) {
                men.append(mencion.toString() + "\n\n");
                  
            }
        }
        
        revalidate();
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        men = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(720, 490));
        setMinimumSize(new java.awt.Dimension(720, 490));
        setPreferredSize(new java.awt.Dimension(720, 490));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        men.setColumns(20);
        men.setRows(5);
        jScrollPane1.setViewportView(men);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 700, 400));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel1.setText("Menciones...");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 340, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea men;
    // End of variables declaration//GEN-END:variables
}
