/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;


import Code.Twits;
import Code.Usuario;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class OtroPerfil extends javax.swing.JFrame {

    /**
     * Creates new form OtroPerfil
     */
  
    Usuario usuario;
    //SyS sys = new SyS(100);
    
    public OtroPerfil(Usuario usuario) {
       initComponents();
        this.usuario=usuario;
         
        Usuario usuarioActual = usuario.getUser();
        Usuario usuarioPerfil = usuario;// perfil que se esta viendo
         
            if (usuarioActual.equals(usuarioPerfil)) {
            bnSeguir.setEnabled(false);
            }
            else{
                bnSeguir.setEnabled(true);
            }
           
         //info en labels 
         
         lbfecha.setText(usuario.getFecha());
         lbedad.setText(Integer.toString(usuario.getEdad()));
         char gen = usuario.getGenero();
         lbsiguiendo.setText(Integer.toString(usuario.getCantidadSeguidos()));
         lbseguidores.setText(Integer.toString(usuario.getCantidadSeguidores()));
         lbnombre1.setText(usuario.getNombre_user());
         bnuser.setText(usuario.getUsername());
         
         //mostrar gen
         if(gen=='M'){
             lbgenero.setText("Masculino");}
         else if (gen=='F'){
             lbgenero.setText("Femenino");
         }
         
         
          String rutaImagen = "";
         if (gen == 'M') {
            rutaImagen = "/Images/maleazul128.png"; 
        } else if (gen == 'F') {
            rutaImagen = "/Images/femaleazul128.png"; 
        }
         
            java.net.URL imgURL = getClass().getResource(rutaImagen);
        if (imgURL != null) {
            ImageIcon imagenIcon = new ImageIcon(imgURL);
            jLabel2.setIcon(imagenIcon);
        } else {
            System.err.println("No se pudo encontrar la imagen en la ruta: " + rutaImagen);
        }
        
        
        jTextArea1.setText("");
        
         Twits[] twits = usuario.getTwits();

        // Recorremos el arreglo en orden inverso
        for (int i = twits.length - 1; i >= 0; i--) {
            if (twits[i] != null) {
                jTextArea1.append(twits[i].toString() + "\n\n");
            }
        }
        
        revalidate();
        repaint();
        
         if (usuarioActual.getSyS().esSeguido(usuarioPerfil)){
           
    bnSeguir.setText("Dejar de Seguir");
    } else {
    

   
    bnSeguir.setText("Seguir");
        
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        lbsiguiendo = new javax.swing.JLabel();
        bnseguidos = new javax.swing.JButton();
        bnseguidores = new javax.swing.JButton();
        lbseguidores = new javax.swing.JLabel();
        bnuser = new javax.swing.JButton();
        lbfecha = new javax.swing.JLabel();
        lbfecha1 = new javax.swing.JLabel();
        bnSeguir = new javax.swing.JButton();
        bnback = new javax.swing.JButton();
        Fonde = new javax.swing.JLabel();
        lbcalendario1 = new javax.swing.JLabel();
        area = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lbnombre1 = new javax.swing.JLabel();
        lbgenero = new javax.swing.JLabel();
        lbedad = new javax.swing.JLabel();
        lbnombre5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/perfil4 (1)perfil5.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 150));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo6.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 880, 190));

        lbsiguiendo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        lbsiguiendo.setForeground(new java.awt.Color(255, 255, 255));
        lbsiguiendo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbsiguiendo.setText("50");
        getContentPane().add(lbsiguiendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 50, 30));

        bnseguidos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        bnseguidos.setText("Siguiendo");
        bnseguidos.setBorderPainted(false);
        bnseguidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bnseguidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnseguidosActionPerformed(evt);
            }
        });
        getContentPane().add(bnseguidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 120, 30));

        bnseguidores.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        bnseguidores.setText("Seguidos");
        bnseguidores.setBorderPainted(false);
        bnseguidores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bnseguidores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bnseguidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnseguidoresActionPerformed(evt);
            }
        });
        getContentPane().add(bnseguidores, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, 120, 30));

        lbseguidores.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        lbseguidores.setForeground(new java.awt.Color(255, 255, 255));
        lbseguidores.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbseguidores.setText("50");
        getContentPane().add(lbseguidores, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, 50, 30));

        bnuser.setBackground(new java.awt.Color(0, 153, 255));
        bnuser.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        bnuser.setForeground(new java.awt.Color(0, 0, 0));
        bnuser.setText("username");
        bnuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnuserActionPerformed(evt);
            }
        });
        getContentPane().add(bnuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 390, 20));

        lbfecha.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        lbfecha.setForeground(new java.awt.Color(255, 255, 255));
        lbfecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbfecha.setText("10/12/15");
        getContentPane().add(lbfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 100, 25));

        lbfecha1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        lbfecha1.setForeground(new java.awt.Color(255, 255, 255));
        lbfecha1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbfecha1.setText("Se unió en");
        getContentPane().add(lbfecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 90, 25));

        bnSeguir.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        bnSeguir.setText("Seguir");
        bnSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnSeguirActionPerformed(evt);
            }
        });
        getContentPane().add(bnSeguir, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 130, 30));

        bnback.setBackground(new java.awt.Color(255, 255, 255));
        bnback.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        bnback.setForeground(new java.awt.Color(0, 153, 255));
        bnback.setText("X ");
        bnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnbackActionPerformed(evt);
            }
        });
        getContentPane().add(bnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 30));

        Fonde.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Fonde, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 10, 730));

        lbcalendario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calendarazul24.png"))); // NOI18N
        getContentPane().add(lbcalendario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        area.setBackground(new java.awt.Color(51, 51, 51));
        area.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout areaLayout = new javax.swing.GroupLayout(area);
        area.setLayout(areaLayout);
        areaLayout.setHorizontalGroup(
            areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, areaLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        areaLayout.setVerticalGroup(
            areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(area, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 920, 350));

        lbnombre1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lbnombre1.setForeground(new java.awt.Color(255, 255, 255));
        lbnombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbnombre1.setText("Nombre Completo");
        getContentPane().add(lbnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 380, 25));

        lbgenero.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        lbgenero.setForeground(new java.awt.Color(255, 255, 255));
        lbgenero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbgenero.setText("Genero");
        getContentPane().add(lbgenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 100, 25));

        lbedad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        lbedad.setForeground(new java.awt.Color(255, 255, 255));
        lbedad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbedad.setText("Edad");
        getContentPane().add(lbedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 40, 25));

        lbnombre5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        lbnombre5.setForeground(new java.awt.Color(255, 255, 255));
        lbnombre5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbnombre5.setText("años");
        getContentPane().add(lbnombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 70, 25));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnseguidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnseguidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnseguidosActionPerformed

    private void bnseguidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnseguidoresActionPerformed

    }//GEN-LAST:event_bnseguidoresActionPerformed

    private void bnuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnuserActionPerformed

    }//GEN-LAST:event_bnuserActionPerformed

    private void bnSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnSeguirActionPerformed
    Usuario usuarioActual = usuario.getUser();
    
    
    Usuario usuarioPerfil = usuario;

    if (usuarioActual.getSyS().esSeguido(usuarioPerfil)) {

      usuarioActual.getSyS().eliminarSeguido(usuarioPerfil);
      usuarioPerfil.getSyS().eliminarSeguidor(usuarioActual);
      bnSeguir.setText("Seguir");
     } else {
    usuarioActual.getSyS().agregarSeguido(usuarioPerfil);
    usuarioPerfil.getSyS().agregarSeguidor(usuarioActual);

    bnSeguir.setText("Dejar de seguir");
    }   
   
    revalidate();
    repaint();

    }//GEN-LAST:event_bnSeguirActionPerformed

    private void bnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnbackActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_bnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtroPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtroPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtroPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtroPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OtroPerfil().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fonde;
    private javax.swing.JPanel area;
    private javax.swing.JButton bnSeguir;
    private javax.swing.JButton bnback;
    private javax.swing.JButton bnseguidores;
    private javax.swing.JButton bnseguidos;
    private javax.swing.JButton bnuser;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbcalendario1;
    private javax.swing.JLabel lbedad;
    private javax.swing.JLabel lbfecha;
    private javax.swing.JLabel lbfecha1;
    private javax.swing.JLabel lbgenero;
    private javax.swing.JLabel lbnombre1;
    private javax.swing.JLabel lbnombre5;
    private javax.swing.JLabel lbseguidores;
    private javax.swing.JLabel lbsiguiendo;
    // End of variables declaration//GEN-END:variables
}
