/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import Code.ManejoUsuario;
import Code.Twits;
import Code.Usuario;
import javax.swing.JSeparator;

/**
 *
 * @author karen
 */
public class TimeLine extends javax.swing.JPanel {

    /**
     * Creates new form TimeLine
     */
    
    private ManejoUsuario user; 
    
    public TimeLine(ManejoUsuario user) {
        this.user=user;
        initComponents();
        area.setLineWrap(true);  
        area.setWrapStyleWord(true);
        
        mostrarTwit();
       
        
        
    }

    
  
    public void mostrarTwit() {
        area.setText("");
        
        /*----------------Twits[] twits = user.obtenerTwitsActual();

        // Recorremos el arreglo en orden inverso
        for (int i = twits.length - 1; i >= 0; i--) {
            if (twits[i] != null) {
                area.append(twits[i].toString() + "\n\n");
            }
        }
        
        revalidate();
        repaint();----------*/
        
        Usuario usuarioActual = user.obtenerUsuarioActual();
        StringBuilder twitsAcumulados = new StringBuilder();

        Twits[] twitsActual = usuarioActual.getTwits();

        for (int i = twitsActual.length - 1; i >= 0; i--) {
            if (twitsActual[i] != null) {
                twitsAcumulados.append(twitsActual[i].toString()).append("\n\n");
            }
        }


          Usuario[] usuariosSeguidos = usuarioActual.obtenerSeguidos();
    
            for (Usuario seguido : usuariosSeguidos) {
                if (seguido.isActivo()) {
                    Twits[] twitsSeguido = seguido.getTwits();
                    
                    for (int i = twitsSeguido.length - 1; i >= 0; i--) { 
                        if (twitsSeguido[i] != null) {
                            twitsAcumulados.append(twitsSeguido[i].toString3()).append("\n\n");
                        }
                    }
                }
            }

        area.setText(twitsAcumulados.toString());

        revalidate();
        repaint();

        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        setPreferredSize(new java.awt.Dimension(720, 490));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Descubre lo que están diciedo...");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 340, -1));

        area.setEditable(false);
        area.setBackground(new java.awt.Color(0, 0, 0));
        area.setColumns(20);
        area.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        area.setForeground(new java.awt.Color(255, 255, 255));
        area.setRows(5);
        area.setBorder(null);
        jScrollPane1.setViewportView(area);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 700, 410));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
